version: "3.3"

services: # Palabra clave de Docker Compose.
  nginx: # Palabra no clave, descriptiva de un servicio.
    image: nginx:alpine # Imagen a extraer desde Docker Hub.
    ports: # Mapeado de puertos entre la máquina real y el contenedor.
      - "8080:80"
    networks: # Este servicio pertenece a la red: internal
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal

networks:
  internal: # Nombre de la red.
    driver: bridge # Modo de conexión.
