
services: # Palabra clave de Docker Compose.
  nginx: # Palabra no clave, descriptiva de un servicio.
    image: nginx:alpine # Imagen a extraer desde Docker Hub.
    ports: # Mapeado de puertos entre la máquina real y el contenedor.
      - "8080:80"
    networks: # Este servicio pertenece a la red: internal
      - internal
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ikanaide
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '4306:3306'
    expose:
      - '3306'
    volumes:
      - ./database/ikanaide0531.sql:/docker-entrypoint-initdb.d/dump.sql
      - db:/var/lib/mysql
    networks:
      - internal

volumes:
  db:
    driver: local

networks:
  internal: # Nombre de la red.
    driver: bridge # Modo de conexión.